### ISSUE TITLE
Only question

### ISSUE THREAD

**Issue by RidleyDragon** [therealcouchpotato/nonaxe#1]
You said about using CP2102. Do you mean USB->TTL converter like this: http://ecx.images-amazon.com/images/I/71l8rOmhEGL._SL1500_.jpg
How we can take advantage of this module? I was looking over the Internet and don't find any schematics with CP2102 (or any other USB-TTL converter) and season interface. 
As far I know it isn't possible to connect TTL converter to a device that has a communication port described as RS232 COM (DB9), which is used by the most of season interfaces.
Or maybe we can connect some TTL pins direct do ISO7816 pins?
Could you provide any schematics?

Thank you in advance

**Comment by therealcouchpotato** [comment]
You can use the CP2102 directly in most situations. IF I remember correctly you need to connect RXD directly to the card's I/O pin along with TXD through a reverse diode (eg. TXD -<|- I/O) to get the single-wire interface working. Then choose one of the flow control outputs to drive the Reset pin. YMMV.

ps. You may also have to remove or disconnect (ie. cut the traces of) the rs232 interface circuitry on the old season board if you're using one of those.
